In [1]:
import numpy as np 

In [4]:
a=np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [5]:
b=np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [6]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
print(c[1][2])       #works on zero based indexes

6


### create zeroes,ones,custom array

In [9]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [12]:
#identity matrix-size/square matrix
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#randommatrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0.05270433 0.98601263 0.84645135]
 [0.69444444 0.7502988  0.29812051]]


In [15]:
print(randomMatrix[:,2])

[0.84645135 0.29812051]


In [16]:
print(randomMatrix[1,1:3])

[0.7502988  0.29812051]


In [17]:
randomMatrix[1,1:3]=1   #slicing
print(randomMatrix)

[[0.05270433 0.98601263 0.84645135]
 [0.69444444 1.         1.        ]]


In [27]:
a=np.zeros((3,3), dtype=np.int64)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
a[:,2]=6
a[1,:]=3        #numpy arrays are mutable

In [29]:
print(a)

[[0 0 6]
 [3 3 3]
 [0 0 6]]


In [30]:
#datatypes
print(a.dtype)

int64


### mathematiclal operations

In [34]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,2,3],[4,5,6]])

print(x+y)

[[ 2  4  6]
 [ 8 10 12]]


In [36]:
print(np.add(x,y))

[[ 2  4  6]
 [ 8 10 12]]


In [37]:
print(x-y)

[[0 0 0]
 [0 0 0]]


In [38]:
print(x*y)

[[ 1  4  9]
 [16 25 36]]


In [39]:
np.multiply(x,y)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [40]:
np.divide(x,y)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
print(np.sqrt(x))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### Matrix multiplication and dot products

In [53]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2,3],[3,4,5]])

print(a.dot(b)) 

[[ 7 10 13]
 [15 22 29]]


In [54]:
print(np.dot(a,b))

[[ 7 10 13]
 [15 22 29]]


### Multiplication of vector

In [56]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [57]:
print(a)

[1 2 3 4]


In [58]:
print(sum(a))

10


In [59]:
print(x)

[[1 2 3]
 [4 5 6]]


In [60]:
print(np.sum(x))

21


In [61]:
print(np.sum(x,axis=0))  #adding elements of the coloumn

[5 7 9]


In [62]:
print(np.sum(x,axis=1))  #adding elements of row

[ 6 15]


### stacking of arrays

In [64]:
a=np.array([1,2,3,4])
print(a)
b=a**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [68]:
x=np.stack((a,b),axis=0)
print(x)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [66]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

### Reshape of array

In [74]:
x=x.reshape(8,1)
print(x)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [75]:
x=x.reshape(4,-1)
print(x)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


### Statistics

In [78]:
a=np.array([[1,2,3,4],[7,6,4,0]])

In [79]:
print(a)
print(np.min(a))

[[1 2 3 4]
 [7 6 4 0]]
0


In [80]:
print(np.min(a,axis=0))

[1 2 3 0]


In [81]:
print(np.max(a,axis=1))

[4 7]


In [84]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  3.5 2. ]
[2.5  4.25]


In [89]:
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [95]:
#mean vs average is weighted
print(np.mean(c))
print(np.average(c))
w=np.array([1,2,3,4,5])

#weights
print(np.average(c,weights=w))

#standard deviation
x=np.std(c)
print(x)

#variance
x=np.var(c)
print(x)

2.4
2.4
2.066666666666667
1.854723699099141
3.4400000000000004


### Random numpy modules

In [4]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a=np.arange(10)*5
print(a)

[ 0  5 10 15 20 25 30 35 40 45]


In [12]:
np.random.shuffle(a)
print(a)

[25  5  0 15 30 20 45 35 40 10]


In [14]:
#returns value from standard normal distribution
x=np.random.rand(2,3)
print(x)

[[0.997495   0.93827484 0.19761704]
 [0.85519779 0.41304026 0.84788175]]


In [22]:
y=np.random.randint(5,120,3)
print(y)

[87 38 28]


In [24]:
#randomly pick one element from an array
element=np.random.choice(a)
print(element)

45


In [35]:
a=np.arange(10)
np.random.seed(2)
np.random.shuffle(a)
print(a)

[4 1 5 0 7 2 3 6 9 8]


In [44]:
a=np.array([1,2])
b=np.array([2,1])
d=0
for e,f in zip(a,b):
    d=d+e*f
print(d)

4


In [45]:
a.dot(b)

4

In [48]:
amag=np.linalg.norm(a)    #for calculating magnitude of a
bmag=np.linalg.norm(b)
cosangle=a.dot(b)/(amag*bmag)

In [49]:
print(cosangle)

0.7999999999999998


In [52]:
angle=np.arccos(cosangle)  #angle will come in radians by default
print(angle)

0.6435011087932847


In [56]:
a=np.random.randn(5,5)
print(a)


[[ 0.21819577 -0.04193043  0.72905905  1.17859548  1.91567888]
 [-1.66040484 -0.49298526 -0.09608246  0.75365793  0.64963618]
 [ 0.03593418  0.74161405 -0.56869514 -0.38453333  0.27772182]
 [-1.08067527  1.53873599 -0.80796499 -1.14380083  0.29669514]
 [-1.92074773 -0.44728372 -0.18530621  1.25356725  3.00943119]]


### time complexity comparison between numpy array dot product and loop dot product

In [72]:
import numpy as np
from datetime import datetime
a=np.random.randn(100)
b=np.random.randn(100)
T=100000

def slow_product(a,b):
    result=0
    for e,f in zip(a,b):
        result=result+(e*f)
    return result

t0=datetime.now()

for t in range(T):
    slow_product(a,b)
t1=datetime.now()-t0

t0=datetime.now()
for t in range(T):
    a.dot(b)
t2=datetime.now()-t0

ratio=t1/t2
print(ratio)
    
        


123.02488734503028


In [98]:
a=np.array([[1,2],[5,3]])
a.T

array([[1, 5],
       [2, 3]])

In [99]:
a=np.array([[1,2],[3,4]])
ainv=np.linalg.inv(a)
print(ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [100]:
a.dot(ainv)   #will give us an identity matrix

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [101]:
np.linalg.det(a)

-2.0000000000000004

In [102]:
np.diag(a)

array([1, 4])

In [103]:
np.diag(a).sum()

5

In [104]:
np.trace(a)

5

In [88]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [92]:
a=np.array([1,2])
b=np.array([3,4])

x=np.outer(a,b)
print(x)              #elemental product

np.inner(a,b)   #dot product

[[3 4]
 [6 8]]


11

In [108]:
x=np.random.randn(100,3)
cov=np.cov(x.T)
cov.shape

(3, 3)

In [109]:
cov

array([[ 1.33989292,  0.21281104,  0.21305949],
       [ 0.21281104,  1.07770338, -0.07361438],
       [ 0.21305949, -0.07361438,  1.28172158]])

In [110]:
np.linalg.eigh(cov)         #eigh gives both eigenvalues and eigenvectors

(array([0.88073478, 1.26118239, 1.55740071]),
 array([[-0.53455739, -0.28552711, -0.79543866],
        [ 0.73407106, -0.62326545, -0.26959203],
        [ 0.4187936 ,  0.72802091, -0.54276834]]))

In [115]:
np.linalg.eig(cov)

(array([0.88073478, 1.55740071, 1.26118239]),
 array([[ 0.53455739, -0.79543866, -0.28552711],
        [-0.73407106, -0.26959203, -0.62326545],
        [-0.4187936 , -0.54276834,  0.72802091]]))

### solution of linear systems

In [121]:
a=np.array([[1,2],[3,4]])
b=np.array([1,2])

x=np.linalg.inv(a).dot(b)
print(x)

[0.  0.5]


In [123]:
x=np.linalg.solve(a,b)
print(x)

[0.  0.5]


In [127]:
a=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])
x=np.linalg.solve(a,b)
print(x)

[1500.  700.]
